---
version: 1
dependencies:
  galaxy: requirements.yml
  python: requirements.txt
  system: bindep.txt
additional_build_steps:
  append:
    - RUN alternatives --set python /usr/bin/python3
    - COPY --from=quay.io/project-receptor/receptor:0.9.7 /usr/bin/receptor /usr/bin/receptor
    - RUN mkdir -p /var/run/receptor
    - RUN pip uninstall ansible-runner -y && pip install git+https://github.com/ansible/ansible-runner.git
    - RUN pip uninstall urllib3 -y && pip install urllib3
