collections:
  - name: awx.awx
  - name: azure.azcollection
  - name: amazon.aws
  - name: theforeman.foreman
  - name: google.cloud
  - name: openstack.cloud
  - name: community.vmware
  - name: ovirt.ovirt
  - name: ansible.posix
  - name: ansible.windows
  - name: community.general
  - name: community.windows
#   - name: community.kubevirt
  - name: https://github.com/ansible-collections/community.kubevirt.git
    type: git
    version: main
  - name: community.okd
  - name: kubernetes.core
    version: 2.1.1
  - name: ansible.netcommon