collections:
  - name: awx.awx
  - name: azure.azcollection
  - name: amazon.aws
  - name: amazon.cloud
  - name: theforeman.foreman
  - name: google.cloud
  - name: openstack.cloud
  - name: community.vmware
  - name: community.aws
  - name: ovirt.ovirt
  - name: ansible.posix
  - name: ansible.windows
  - name: community.general
  - name: community.windows
  - name: community.azure
  - name: community.kubernetes
#  - name: community.kubevirt # disable as it's not compatible with the latest version of Ansible
  - name: community.okd
  - name: community.postgresql
  - name: kubernetes.core
  - name: ansible.netcommon
  - name: vmware.vmware_rest
  #- name: chocolatey.chocolatey # requirements conflict with community.vmware
  - name: https://github.com/oatakan/chocolatey-ansible.git#/chocolatey/
    type: git
    version: update_reqs